### ISSUE TITLE
Element not visible

### ISSUE THREAD

**Issue by retroriff** [CodyHouse/cd-language-picker-changelog#1]
Hello, the JS of this component is not being loaded, so the element is hidden:

https://www.fanaticguitars.com/download/language/

Am I missing something?

Thank you

**Comment by claudia-romano** [comment]
Hi there, could you please double check you are importing the js code of the language picker component? I checked your script.js and it looks like it includes only the utility functions of the framework. Thanks.

**Comment by retroriff** [comment]
Hi, I added the js code of the language picker component in a inline script at the head.

**Comment by claudia-romano** [comment]
Could you please import the inline code after the script.js file? Right before the <body> closing tag. Thanks

**Comment by retroriff** [comment]
Excellent, that works! Actually I detected that the error was caused by a mistake editing the JS. Thank you very much. It is an excellent framework.
