### ISSUE TITLE
Demo does not work in ReactJS

### ISSUE THREAD

**Issue by kryloff** [CodyHouse/cd-language-picker-changelog#2]
Hi!  ReactJS doesn't add the `selected` attribute to the select option, so the demo crashes with an error. Easy to edit by replacing the check from
`var selected = picker.options[i].hasAttribute('selected') ? ' aria-selected="true"' : '',`
to
`var selected = picker.options[i].selected ? ' aria-selected="true"' : '',`

**Comment by claudia-romano** [comment]
Thanks for the heads-up! This has been fixed now.
